Repository jfrog/ide-plugins-common, pull requests merged in 2023-01, with the labels that each got.

#94 Add new IssueTreeNode for applicability scanning view
  build.gradle
  src/main/java/com/jfrog/ide/common/tree/ApplicableIssueNode.java
  src/main/java/com/jfrog/ide/common/tree/DescriptorFileTreeNode.java
  src/main/java/com/jfrog/ide/common/tree/FileTreeNode.java
  src/main/java/com/jfrog/ide/common/tree/IssueNode.java
  src/main/java/com/jfrog/ide/common/utils/Utils.java
Labels: new feature

#97 Add new No-Applicable severity type
  src/main/java/com/jfrog/ide/common/tree/BaseTreeNode.java
  src/main/java/com/jfrog/ide/common/tree/ComparableSeverityTreeNode.java
  src/main/java/com/jfrog/ide/common/tree/DependencyNode.java
  src/main/java/com/jfrog/ide/common/tree/DescriptorFileTreeNode.java
  src/main/java/com/jfrog/ide/common/tree/FileTreeNode.java
  src/main/java/com/jfrog/ide/common/tree/IssueNode.java
  src/main/java/com/jfrog/ide/common/tree/Severity.java
  src/main/java/com/jfrog/ide/common/tree/VulnerabilityOrViolationNode.java
Labels: improvement

#98 Remove "unresolved" from Gradle nodes
  src/main/java/com/jfrog/ide/common/gradle/GradleTreeBuilder.java
  src/test/java/com/jfrog/ide/common/gradle/GradleTreeBuilderTest.java
Labels: bug

#99 Added scannerSearchTarget in ApplicableIssueNode
  src/main/java/com/jfrog/ide/common/tree/ApplicableIssueNode.java
Labels: improvement

#101 V1: Skip loading cache from file system in full scan mode
  src/main/java/com/jfrog/ide/common/persistency/XrayScanCache.java
  src/main/java/com/jfrog/ide/common/scan/ComponentSummaryScanLogic.java
  src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
  src/main/java/com/jfrog/ide/common/scan/ScanLogic.java
  src/main/java/com/jfrog/ide/common/scan/ScanManagerBase.java
  src/test/java/com/jfrog/ide/common/persistency/ScanCacheTest.java
  src/test/java/com/jfrog/ide/common/scan/GraphScanLogicTest.java
  src/test/java/com/jfrog/ide/common/scan/ScanLogicTest.java
Labels: bug

#100 Changes to support IDEA code inspections
  src/main/java/com/jfrog/ide/common/tree/DependencyNode.java
  src/main/java/com/jfrog/ide/common/tree/DescriptorFileTreeNode.java
  src/main/java/com/jfrog/ide/common/tree/FileTreeNode.java
  src/main/java/com/jfrog/ide/common/tree/GeneralInfo.java
  src/main/java/com/jfrog/ide/common/tree/ImpactTreeNode.java
  src/main/java/com/jfrog/ide/common/utils/Utils.java
Labels: ignore for release

#104 Upgrade to gradle 7.6
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: improvement

#102 Add new "not applicable severity" types
  src/main/java/com/jfrog/ide/common/tree/ApplicableIssueNode.java
  src/main/java/com/jfrog/ide/common/tree/ComparableSeverityTreeNode.java
  src/main/java/com/jfrog/ide/common/tree/IssueNode.java
  src/main/java/com/jfrog/ide/common/tree/Severity.java
Labels: improvement
