Repository jfrog/ide-plugins-common, pull requests merged in 2023-02, with the labels that each got.

#103 Add support for issue's ignore rule creation
  build.gradle
  src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
  src/main/java/com/jfrog/ide/common/tree/IssueNode.java
Labels: improvement

#106 Restructure
  src/main/java/com/jfrog/ide/common/nodes/ApplicableIssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/DependencyNode.java
  src/main/java/com/jfrog/ide/common/nodes/DescriptorFileTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/FileTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/ImpactTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/IssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/LicenseViolationNode.java
  src/main/java/com/jfrog/ide/common/nodes/SortableChildrenTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/SubtitledTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/VulnerabilityNode.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/Cve.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/License.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/ResearchInfo.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/Severity.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/SeverityReason.java
  src/main/java/com/jfrog/ide/common/scan/ComponentPrefix.java
  src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
  src/main/java/com/jfrog/ide/common/scan/ScanLogic.java
  src/main/java/com/jfrog/ide/common/tree/BaseTreeNode.java
  src/main/java/com/jfrog/ide/common/tree/ComparableSeverityTreeNode.java
  src/main/java/com/jfrog/ide/common/tree/DependencyNode.java
  src/main/java/com/jfrog/ide/common/tree/GeneralInfo.java
  src/main/java/com/jfrog/ide/common/tree/VulnerabilityOrViolationNode.java
  src/main/java/com/jfrog/ide/common/utils/Utils.java
Labels: improvement

#108 Fix Issues' Severities Hierarchy
  src/main/java/com/jfrog/ide/common/nodes/subentities/Severity.java
Labels: bug

#107 Update gradle-dep-tree
  build.gradle
  src/test/java/com/jfrog/ide/common/gradle/GradleTreeBuilderTest.java
Labels: ignore for release

#111 Support Download the AnalyzerManager
  build.gradle
  src/main/java/com/jfrog/ide/common/nodes/DependencyNode.java
  src/main/java/com/jfrog/ide/common/utils/ArtifactoryConnectionUtils.java
Labels: ignore for release

#109 Cache last scan results
  src/main/java/com/jfrog/ide/common/nodes/ApplicableIssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/DependencyNode.java
  src/main/java/com/jfrog/ide/common/nodes/DescriptorFileTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/FileTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/IssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/LicenseViolationNode.java
  src/main/java/com/jfrog/ide/common/nodes/SortableChildrenTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/VulnerabilityNode.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/ImpactTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/License.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/ResearchInfo.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/SeverityReason.java
  src/main/java/com/jfrog/ide/common/persistency/ScanCache.java
  src/main/java/com/jfrog/ide/common/persistency/ScanCacheObject.java
  src/main/java/com/jfrog/ide/common/scan/GraphScanLogic.java
Labels: improvement

#112 Fix writing private and protected fields to cache
  build.gradle
  src/main/java/com/jfrog/ide/common/ci/XrayBuildDetailsDownloader.java
  src/main/java/com/jfrog/ide/common/nodes/ApplicableIssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/DependencyNode.java
  src/main/java/com/jfrog/ide/common/nodes/FileTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/IssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/LicenseViolationNode.java
  src/main/java/com/jfrog/ide/common/nodes/SortableChildrenTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/VulnerabilityNode.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/Cve.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/ImpactTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/License.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/ResearchInfo.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/SeverityReason.java
Labels: bug
