Repository jfrog/ide-plugins-common, pull requests merged in 2023-08, with the labels that each got.

#127 Adds createSSLContext Utility
  build.gradle
  src/main/java/com/jfrog/ide/common/utils/ArtifactoryConnectionUtils.java
  src/main/java/com/jfrog/ide/common/utils/Utils.java
Labels: improvement

#121 Support login by Web
  src/main/java/com/jfrog/ide/common/configuration/JfrogCliServerConfig.java
  src/main/java/com/jfrog/ide/common/utils/ArtifactoryConnectionUtils.java
  src/main/java/com/jfrog/ide/common/utils/Utils.java
  src/main/java/com/jfrog/ide/common/utils/XrayConnectionUtils.java
  src/test/java/com/jfrog/ide/common/utils/ConsolidatePathsTest.java
  src/test/java/com/jfrog/ide/common/utils/UtilsTest.java
Labels: improvement

#128 Created ImpactTree class
  src/main/java/com/jfrog/ide/common/nodes/DependencyNode.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/ImpactTree.java
  src/main/java/com/jfrog/ide/common/persistency/ScanCache.java
  src/main/java/com/jfrog/ide/common/persistency/ScanCacheObject.java
Labels: improvement

#129 Fix duplications in results cache
  src/main/java/com/jfrog/ide/common/nodes/ApplicableIssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/DependencyNode.java
  src/main/java/com/jfrog/ide/common/nodes/FileIssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/FileTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/Severity.java
  src/test/java/com/jfrog/ide/common/persistency/ScanCacheTest.java
Labels: bug

#131 Fix errors when scanning projects using Gradle <7.6
  src/main/resources/gradle-dep-tree.gradle
Labels: bug

#130 Add EOS entities
  src/main/java/com/jfrog/ide/common/nodes/ApplicableIssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/EosIssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/FileIssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/FindingInfo.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/SourceCodeScanType.java
  src/test/java/com/jfrog/ide/common/persistency/ScanCacheTest.java
Labels: ignore for release
