Repository jfrog/ide-plugins-common, pull requests merged in 2023-09, with the labels that each got.

#133 Ignore false secret issues
  src/main/java/com/jfrog/ide/common/configuration/JfrogCliServerConfig.java
Labels: ignore for release

#135 Update build info version to 2.41.6
  build.gradle
Labels: improvement

#136 Fix NullPointerException when scanning Go modules with no packages
  src/main/java/com/jfrog/ide/common/go/GoTreeBuilder.java
  src/test/java/com/jfrog/ide/common/go/GoTreeBuilderTest.java
  src/test/resources/go/project5/go.mod
  src/test/resources/go/project5/go.sum
  src/test/resources/go/project5/main.go
  src/test/resources/go/project6/go.mod
  src/test/resources/go/project6/go.sum
Labels: bug
