Repository jfrog/ide-plugins-common, pull requests merged in 2023-10, with the labels that each got.

#134 Add Support to the New Scanners Config
  src/main/java/com/jfrog/ide/common/nodes/SastIssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/SourceCodeScanType.java
Labels: ignore for release

#139 Adds new EcosystemUsageReporter Utility
  src/main/java/com/jfrog/ide/common/ci/CiManagerBase.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/ApplicableInfo.java
  src/main/java/com/jfrog/ide/common/utils/usage/EcosystemUsageReporter.java
  src/main/java/com/jfrog/ide/common/utils/usage/UsageReport.java
Labels: new feature

#138 Merge file nodes
  src/main/java/com/jfrog/ide/common/nodes/FileTreeNode.java
Labels: improvement
