Repository jfrog/ide-plugins-common, pull requests merged in 2025-03, with the labels that each got.

#164 Update test.yml
  .github/workflows/test.yml
Labels: ignore for release

#163 Improvement/tests run in real env
  .github/workflows/test.yml
  src/test/java/com/jfrog/ide/common/configuration/JfrogCliDriverTest.java
Labels: improvement, safe to test

#162 Added support for cli audit
  .gitignore
  src/main/java/com/jfrog/ide/common/configuration/JfrogCliDriver.java
  src/test/java/com/jfrog/ide/common/configuration/JfrogCliDriverTest.java
  src/test/resources/example-projects/maven-example/multi1/pom.xml
  src/test/resources/example-projects/maven-example/multi2/pom.xml
  src/test/resources/example-projects/maven-example/multi3/pom.xml
  src/test/resources/example-projects/maven-example/pom.xml
  src/test/resources/example-projects/npm/@fo/asbcd.js
  src/test/resources/example-projects/npm/package-lock.json
  src/test/resources/example-projects/npm/package.json
Labels: improvement

#166 Add Parser for Jfrog Cli SARIF Reports
  build.gradle
  src/main/java/com/jfrog/ide/common/nodes/FileIssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/FileTreeNode.java
  src/main/java/com/jfrog/ide/common/nodes/SastIssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/ScaIssueNode.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/ImpactPath.java
  src/main/java/com/jfrog/ide/common/nodes/subentities/SourceCodeScanType.java
  src/main/java/com/jfrog/ide/common/parse/Applicability.java
  src/main/java/com/jfrog/ide/common/parse/SarifParser.java
  src/test/java/com/jfrog/ide/common/parse/SarifParserTest.java
  src/test/resources/parse/code_flows_in_sast.json
  src/test/resources/parse/invalid_sarif.json
  src/test/resources/parse/invalid_sarif_no_results.json
  src/test/resources/parse/sca_iac_secrets_sast.json
  src/test/resources/parse/sca_no_jas.json
Labels: new feature

#168 Updated the sarif parser and the version cli func use
  src/main/java/com/jfrog/ide/common/configuration/JfrogCliDriver.java
  src/main/java/com/jfrog/ide/common/parse/SarifParser.java
  src/test/java/com/jfrog/ide/common/configuration/JfrogCliDriverTest.java
Labels: improvement

#169 Add support for configuring environment variables in JfrogCliDriver
  src/main/java/com/jfrog/ide/common/configuration/JfrogCliDriver.java
  src/test/java/com/jfrog/ide/common/configuration/JfrogCliDriverTest.java
Labels: improvement

#171 Add support for presenting FileIssueNode title by calling toString method
  src/main/java/com/jfrog/ide/common/nodes/FileIssueNode.java
Labels: improvement
